package photostock.entities;
// Generated Mar 8, 2018 3:01:44 PM by Hibernate Tools 5.2.3.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.Proxy;

/**
 * Buyer generated by hbm2java
 */
@Entity
@Proxy(lazy=false)
@Table(name = "buyer", catalog = "photostock")
public class Buyer implements java.io.Serializable {

	private Integer id;
	private Date joinDate;
	private boolean enabled;
	private String username;
	private String password;
	private String gmailToken;
	private String fbTocken;
	private int rolePk;
	private String firstName;
	private String lastName;
	private String gender;
	private Date birthday;
	private String phone;
	private String photo;
	private Set<Orders> orderses = new HashSet<Orders>(0);
	private Set<BuyerRole> buyerRoles = new HashSet<BuyerRole>(0);

	public Buyer() {
	}

	public Buyer(Date joinDate, boolean enabled, String username, String password, int rolePk) {
		this.joinDate = joinDate;
		this.enabled = enabled;
		this.username = username;
		this.password = password;
		this.rolePk = rolePk;
	}

	public Buyer(Date joinDate, boolean enabled, String username, String password, String gmailToken, String fbTocken,
			int rolePk, String firstName, String lastName, String gender, Date birthday, String phone, String photo,
			Set<Orders> orderses, Set<BuyerRole> buyerRoles) {
		this.joinDate = joinDate;
		this.enabled = enabled;
		this.username = username;
		this.password = password;
		this.gmailToken = gmailToken;
		this.fbTocken = fbTocken;
		this.rolePk = rolePk;
		this.firstName = firstName;
		this.lastName = lastName;
		this.gender = gender;
		this.birthday = birthday;
		this.phone = phone;
		this.photo = photo;
		this.orderses = orderses;
		this.buyerRoles = buyerRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "join_date", nullable = false, length = 10)
	public Date getJoinDate() {
		return this.joinDate;
	}

	public void setJoinDate(Date joinDate) {
		this.joinDate = joinDate;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "gmail_token", length = 250)
	public String getGmailToken() {
		return this.gmailToken;
	}

	public void setGmailToken(String gmailToken) {
		this.gmailToken = gmailToken;
	}

	@Column(name = "fb_tocken", length = 250)
	public String getFbTocken() {
		return this.fbTocken;
	}

	public void setFbTocken(String fbTocken) {
		this.fbTocken = fbTocken;
	}

	@Column(name = "role_pk", nullable = false)
	public int getRolePk() {
		return this.rolePk;
	}

	public void setRolePk(int rolePk) {
		this.rolePk = rolePk;
	}

	@Column(name = "firstName", length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "lastName", length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "gender", length = 20)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "birthday", length = 10)
	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	@Column(name = "phone", length = 50)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "photo", length = 250)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "buyer")
	public Set<Orders> getOrderses() {
		return this.orderses;
	}

	public void setOrderses(Set<Orders> orderses) {
		this.orderses = orderses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "buyer")
	public Set<BuyerRole> getBuyerRoles() {
		return this.buyerRoles;
	}

	public void setBuyerRoles(Set<BuyerRole> buyerRoles) {
		this.buyerRoles = buyerRoles;
	}

}
