package photostock.entities;
// Generated Mar 8, 2018 3:01:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * BuyerRole generated by hbm2java
 */
@Entity
@Table(name = "buyer_role", catalog = "photostock")
public class BuyerRole implements java.io.Serializable {

	private BuyerRoleId id;
	private Buyer buyer;
	private Role role;
	private boolean enable;

	public BuyerRole() {
	}

	public BuyerRole(BuyerRoleId id, Buyer buyer, Role role, boolean enable) {
		this.id = id;
		this.buyer = buyer;
		this.role = role;
		this.enable = enable;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "buyerPk", column = @Column(name = "buyer_pk", nullable = false)),
			@AttributeOverride(name = "rolePk", column = @Column(name = "role_pk", nullable = false)) })
	public BuyerRoleId getId() {
		return this.id;
	}

	public void setId(BuyerRoleId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "buyer_pk", nullable = false, insertable = false, updatable = false)
	public Buyer getBuyer() {
		return this.buyer;
	}

	public void setBuyer(Buyer buyer) {
		this.buyer = buyer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_pk", nullable = false, insertable = false, updatable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "enable", nullable = false)
	public boolean isEnable() {
		return this.enable;
	}

	public void setEnable(boolean enable) {
		this.enable = enable;
	}

}
