package photostock.entities;
// Generated Mar 8, 2018 3:01:44 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * OrdersdetailId generated by hbm2java
 */
@Embeddable
public class OrdersdetailId implements java.io.Serializable {

	private int itemPk;
	private int ordersPk;

	public OrdersdetailId() {
	}

	public OrdersdetailId(int itemPk, int ordersPk) {
		this.itemPk = itemPk;
		this.ordersPk = ordersPk;
	}

	@Column(name = "item_pk", nullable = false)
	public int getItemPk() {
		return this.itemPk;
	}

	public void setItemPk(int itemPk) {
		this.itemPk = itemPk;
	}

	@Column(name = "orders_pk", nullable = false)
	public int getOrdersPk() {
		return this.ordersPk;
	}

	public void setOrdersPk(int ordersPk) {
		this.ordersPk = ordersPk;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof OrdersdetailId))
			return false;
		OrdersdetailId castOther = (OrdersdetailId) other;

		return (this.getItemPk() == castOther.getItemPk()) && (this.getOrdersPk() == castOther.getOrdersPk());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getItemPk();
		result = 37 * result + this.getOrdersPk();
		return result;
	}

}
