package photostock.entities;
// Generated Mar 8, 2018 3:01:44 PM by Hibernate Tools 5.2.3.Final

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Ordersdetail generated by hbm2java
 */
@Entity
@Table(name = "ordersdetail", catalog = "photostock")
public class Ordersdetail implements java.io.Serializable {

	private OrdersdetailId id;
	private Item item;
	private Orders orders;
	private BigDecimal price;
	private int quantity;

	public Ordersdetail() {
	}

	public Ordersdetail(OrdersdetailId id, Item item, Orders orders, BigDecimal price, int quantity) {
		this.id = id;
		this.item = item;
		this.orders = orders;
		this.price = price;
		this.quantity = quantity;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "itemPk", column = @Column(name = "item_pk", nullable = false)),
			@AttributeOverride(name = "ordersPk", column = @Column(name = "orders_pk", nullable = false)) })
	public OrdersdetailId getId() {
		return this.id;
	}

	public void setId(OrdersdetailId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "item_pk", nullable = false, insertable = false, updatable = false)
	public Item getItem() {
		return this.item;
	}

	public void setItem(Item item) {
		this.item = item;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "orders_pk", nullable = false, insertable = false, updatable = false)
	public Orders getOrders() {
		return this.orders;
	}

	public void setOrders(Orders orders) {
		this.orders = orders;
	}

	@Column(name = "price", nullable = false, precision = 10)
	public BigDecimal getPrice() {
		return this.price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

}
